services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run -token ${TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - application_network

networks:
  application_network:
    driver: bridge
    internal: true
